Repository linear-b/gitstream, pull requests merged in 2023-12, with the labels that each got.

#374 Corrected indentation in "Additional Reviews for large PR" example
  docs/downloads/automation-library/additional_review_for_large_pr.cm
Labels: 1 min review, examples-code-changes

#382 Create new starter example
  docs/downloads/automation-library/standard/gitstream_starter.cm
  docs/examples.md
  mkdocs.yml
Labels: 5 min review, examples-code-changes

#384 Copyedits and improvements to new quick start examples
  docs/downloads/automation-library/standard/label_automation.cm
  docs/downloads/automation-library/standard/review_routing.cm
  docs/examples.md
  docs/screenshots/label-management-starter.png
Labels: 5 min review, examples-code-changes, no screenshot

#383 local plugins - custom filters
  docs/custom-filters-v1.md
  docs/custom-filters.md
Labels: 5 min review

#376 Add genai measurement examples
  docs/automations/automation-library.md
  docs/automations/integrations/copilot/flag-copilot-pr/README.md
  docs/automations/integrations/copilot/flag-copilot-pr/label-copilot-by-contributors.png
  docs/automations/integrations/copilot/flag-copilot-pr/label-copilot-by-prompt.png
  docs/automations/integrations/copilot/flag-copilot-pr/label-copilot-by-tag.png
  docs/downloads/automation-library/integrations/copilot/comment_copilot_prompt.cm
  docs/downloads/automation-library/integrations/copilot/label_copilot_by_contributors.cm
  docs/downloads/automation-library/integrations/copilot/label_copilot_by_prompt.cm
  docs/downloads/automation-library/integrations/copilot/label_copilot_by_tag.cm
  docs/integrations/README.md
  docs/integrations/github-copilot.md
Labels: 5 min review, examples-code-changes

#388 Revamp Readme
  README.md
Labels: 1 min review

#386 New Linearb integration page
  docs/downloads/images/LinearB-logo-dark.png
  docs/downloads/images/LinearB-logo-white.png
  docs/downloads/images/linearb-symbol-dark.png
  docs/downloads/images/linearb-symbol-white.png
  docs/integrations/README.md
  docs/integrations/linearb.md
  docs/stylesheets/extra.css
Labels: 1 min review

#389 remove uder-development from commit message
  docs/context-variables.md
Labels: 1 min review, no screenshot

#392 Update use cases for default gitStream config
  docs/downloads/gitstream.cm
Labels: 1 min review, examples-code-changes

#381 New language-based examples
  docs/automations/automation-library.md
  docs/automations/integrations/linearb/copilot-label-metrics.png
  docs/automations/integrations/linearb/resource-label-metrics.png
  docs/automations/standard/label-management/README.md
  docs/automations/standard/label-management/label-modified-resources/README.md
  docs/automations/standard/label-management/label-prs-by-language/README.md
  docs/automations/standard/label-management/label-prs-by-language/label-prs-by-language.png
  docs/automations/standard/summarize-language-changes/README.md
  docs/automations/standard/summarize-language-changes/summarize-language-changes.png
  docs/downloads/automation-library/standard/label-management/label_prs_by_language.cm
  docs/downloads/automation-library/standard/summarize_language_changes.cm
  docs/integrations/linearb.md
Labels: 5 min review, examples-code-changes

#396 exclude plugins and update material
  docs/custom-filters.md
  requirements.txt
Labels: 1 min review, no screenshot

#398 fix slack typo
  docs/context-variables.md
Labels: 1 min review, no screenshot

#397 steps for self hosted
  docs/github-installation.md
Labels: 1 min review

#399 Custom filters updates
  docs/custom-filters.md
Labels: 1 min review

#401 Update faq.md
  docs/faq.md
  docs/screenshots/merge-queue-check.png
Labels: 1 min review, no screenshot
