Repository linear-b/gitstream, pull requests merged in 2023-08, with the labels that each got.

#274 More SEO fixes and template adjustments
  docs/automations/additional-review-for-large-pr/README.md
  docs/automations/approve-javascript-formatting-change/README.md
  docs/automations/approve-javascript-log-output/README.md
  docs/automations/approve-python-formatting-change/README.md
  docs/automations/approve-python-log-output/README.md
  docs/automations/approve-safe-changes/README.md
  docs/automations/approve-team-by-directory/README.md
  docs/automations/approve-tests/README.md
  docs/automations/approve-tiny-changes/README.md
  docs/automations/assign-code-experts/README.md
  docs/automations/assign-reviewers-by-directory/README.md
  docs/automations/assign-team-members-as-reviewers/README.md
  docs/automations/change-deprecated-components/README.md
  docs/automations/change-missing-lambda-field/README.md
  docs/automations/close-wrong-team-by-directory/README.md
  docs/automations/label-deleted-files/README.md
  docs/automations/label-prs-without-tests/README.md
  docs/automations/languages/css/review-css-important/README.md
  docs/automations/percent-new-code/README.md
  docs/automations/provide-estimated-time-to-review/README.md
  docs/automations/request-screenshot/README.md
  docs/automations/review-sensitive-files/README.md
  docs/automations/standard/explain-code-experts/README.md
  docs/automations/standard/review-changelog/README.md
  docs/automations/standard/share-knowledge/README.md
  docs/automations/utilities/cm-header/README.md
  docs/automations/utilities/colors-custom-expression/README.md
  docs/automations/welcome-newcomer/README.md
  docs/snippets/change-request-automation.md
  docs/snippets/context-automation.md
  docs/snippets/javascript-automation.md
  docs/snippets/python-automation.md
  docs/snippets/review-assignment-automation.md
  docs/snippets/utility-automation.md
  docs/templates/automation-example-template.md
  docs/templates/integration-template.md
Labels: no screenshot

#269 Added Terraform Integration for "Review New Terraform Modules"
  docs/automations/integrations/terraform/review-new-module/README.md
  docs/automations/integrations/terraform/review-new-module/review-new-module.png
  docs/automations/integrations/terraform/review-terraform/review-terraform.png
  docs/downloads/automation-library/integrations/terraform/review_new_module.cm
  docs/integrations/terraform.md
Labels: 5 min review, examples-code-changes, no screenshot

#287 better formatting for troubleshooting
  docs/screenshots/repo_in_org_setup.png
  docs/troubleshooting.md
Labels: 1 min review

#288 fix of nope logic - true on empty lists
  docs/filter-functions.md
Labels: 1 min review

#285 Create Label management use case page
  docs/automations/standard/label-management/README.md
  docs/automations/standard/label-management/enforce-labels/README.md
  docs/automations/standard/label-management/enforce-labels/enforce-labels.png
  docs/automations/standard/label-management/label-approvals/README.md
  docs/automations/standard/label-management/label-approvals/label-approvals.png
  docs/automations/standard/label-management/label-modified-resources/README.md
  docs/automations/standard/label-management/label-modified-resources/label-modified-resources.png
  docs/automations/standard/label-management/label-unresolved-threads/README.md
  docs/automations/standard/label-management/label-unresolved-threads/label-unresolved-threads.png
  docs/automations/standard/label-management/suggest-labels/README.md
  docs/automations/standard/label-management/suggest-labels/suggest-labels.png
  docs/downloads/automation-library/standard/label-management/enforce_required_labels.cm
  docs/downloads/automation-library/standard/label-management/label_approvals.cm
  docs/downloads/automation-library/standard/label-management/label_modified_resources.cm
  docs/downloads/automation-library/standard/label-management/label_unresolved_threads.cm
  docs/downloads/automation-library/standard/label-management/suggest_labels.cm
  docs/integrations/README.md
  docs/snippets/context-automation.md
  docs/templates/automation-example-template.md
Labels: examples-code-changes, 10 min review

#278 Fix Terraform link
  docs/integrations/README.md
Labels: 1 min review, no screenshot

#290 Create new automation examples
  docs/automations/automation-library.md
  docs/automations/standard/branch-management/README.md
  docs/automations/standard/branch-management/enforce-branch-name/README.md
  docs/automations/standard/branch-management/enforce-branch-name/enforce-branch-name.png
  docs/automations/standard/branch-management/review-target-branch/README.md
  docs/automations/standard/branch-management/review-target-branch/review-target-branch.png
  docs/automations/standard/enforce-copyright-header/README.md
  docs/automations/standard/enforce-copyright-header/enforce-copyright-header.png
  docs/automations/standard/enforce-pr-title/README.md
  docs/automations/standard/enforce-pr-title/enforce-pr-title.png
  docs/automations/standard/label-management/README.md
  docs/automations/standard/label-management/label-resources-percent/README.md
  docs/automations/standard/label-management/label-resources-percent/label-resources-percent.png
  docs/automations/standard/label-management/label-unresolved-threads/label-unresolved-threads.png
  docs/downloads/automation-library/standard/branch-management/enforce_branch_name.cm
  docs/downloads/automation-library/standard/branch-management/review_target_branch.cm
  docs/downloads/automation-library/standard/enforce_copyright_header.cm
  docs/downloads/automation-library/standard/enforce_pr_title.cm
  docs/downloads/automation-library/standard/label-management/label_modified_resources.cm
  docs/downloads/automation-library/standard/label-management/label_resources_percent.cm
  docs/integrations/README.md
  docs/templates/integration-template.md
Labels: examples-code-changes, 10 min review

#292 Fix automation name.
  docs/downloads/automation-library/standard/branch-management/review_target_branch.cm
Labels: 1 min review, examples-code-changes

#291 fix share_knowledge name
  docs/downloads/automation-library/standard/share_knowledge.cm
Labels: 1 min review, examples-code-changes

#294 Add GitHub edit button
  mkdocs.yml
Labels: 1 min review

#295 added owner
  docs/context-variables.md
Labels: 1 min review

#296 added wait-foar-all-checks arg
  docs/automation-actions.md
Labels: 1 min review

#299 added capture filter
  docs/filter-functions.md
Labels: 1 min review

#302 Remove redundant title.
  docs/integrations/README.md
Labels: 1 min review, no screenshot

#297 gitlab setup
  2023-07-24.md
  Untitled.canvas
  docs/gitlab-installation.md
  docs/index.md
Labels: 1 min review
