Repository linear-b/gitstream, pull requests merged in 2023-11, with the labels that each got.

#347 remove hacktoberfest
  README.md
Labels: 1 min review

#350 add repo visibility
  docs/context-variables.md
Labels: 1 min review

#351 checks are completed with conclusion
  docs/automation-actions.md
Labels: 1 min review

#354 Language-based test automations
  docs/automations/languages/golang/README.md
  docs/automations/languages/golang/review-missing-golang-tests/README.md
  docs/automations/languages/golang/review-missing-golang-tests/review-missing-golang-tests.png
  docs/automations/languages/java/README.md
  docs/automations/languages/java/review-java-test-name/README.md
  docs/automations/languages/java/review-java-test-name/review-java-test-name.png
  docs/automations/languages/java/review-missing-java-tests/README.md
  docs/automations/languages/java/review-missing-java-tests/review-missing-java-tests.png
  docs/automations/languages/javascript/README.md
  docs/automations/languages/javascript/review-javascript-test-name/README.md
  docs/automations/languages/javascript/review-javascript-test-name/review-javascript-test-name.png
  docs/automations/languages/javascript/review-missing-javascript-tests/README.md
  docs/automations/languages/javascript/review-missing-javascript-tests/review-missing-javascript-tests.png
  docs/automations/languages/python/README.md
  docs/automations/languages/python/review-missing-python-tests/README.md
  docs/automations/languages/python/review-missing-python-tests/review-missing-python-tests.png
  docs/automations/languages/python/review-python-test-name/README.md
  docs/automations/languages/python/review-python-test-name/review-python-test-name.png
  docs/automations/languages/ruby/README.md
  docs/automations/languages/ruby/review-missing-ruby-tests/README.md
  docs/automations/languages/ruby/review-missing-ruby-tests/review-missing-ruby-tests.png
  docs/automations/languages/ruby/review-ruby-test-name/README.md
  docs/automations/languages/ruby/review-ruby-test-name/review-ruby-test-name.png
  docs/downloads/automation-library/languages/golang/review_golang_test_name.cm
  docs/downloads/automation-library/languages/golang/review_missing_golang_tests.cm
  docs/downloads/automation-library/languages/java/review_java_test_name.cm
  docs/downloads/automation-library/languages/java/review_missing_java_tests.cm
  docs/downloads/automation-library/languages/javascript/review_javascript_test_name.cm
  docs/downloads/automation-library/languages/javascript/review_missing_javascript_tests.cm
  docs/downloads/automation-library/languages/python/review_missing_python_tests.cm
  docs/downloads/automation-library/languages/python/review_python_test_name.cm
  docs/downloads/automation-library/languages/ruby/review_missing_ruby_tests.cm
  docs/downloads/automation-library/languages/ruby/review_ruby_test_name.cm
  docs/integrations/golang/golang-testing-automations.md
  docs/integrations/java/java-testing-automations.md
  docs/integrations/javascript/javascript-testing-automations.md
  docs/integrations/python/python-testing-automations.md
  docs/integrations/ruby/ruby-testing-automations.md
Labels: examples-code-changes, 20 min review

#362 HTML Use Cases
  docs/automations/languages/html/README.md
  docs/automations/languages/html/enforce-html-title-length/README.md
  docs/automations/languages/html/enforce-html-title-length/enforce-html-title-length.png
  docs/automations/languages/html/enforce-image-alt/README.md
  docs/automations/languages/html/enforce-image-alt/enforce-image-alt.png
  docs/automations/languages/html/flag-duplicate-h1/README.md
  docs/automations/languages/html/flag-duplicate-h1/flag-duplicate-h1.png
  docs/automations/languages/html/flag-missing-html-tags/README.md
  docs/automations/languages/html/flag-missing-html-tags/flag-missing-html-tags.png
  docs/downloads/automation-library/languages/html/enforce_html_title_length.cm
  docs/downloads/automation-library/languages/html/enforce_image_alt.cm
  docs/downloads/automation-library/languages/html/flag_duplicate_h1.cm
  docs/downloads/automation-library/languages/html/flag_missing_html_tags.cm
  docs/integrations/html/html-css-automations.md
Labels: examples-code-changes, 10 min review

#360 Review Todo comments example
  docs/automations/automation-library.md
  docs/automations/standard/review-todo-comments/README.md
  docs/automations/standard/review-todo-comments/review-todo-comments.png
  docs/downloads/automation-library/standard/review-todo-comments/review_todo_comments.cm
  docs/integrations/review-todo-comments.md
Labels: 5 min review, examples-code-changes

#363 fixed the correctness of the regex
  docs/downloads/automation-library/standard/enforce_pr_title.cm
Labels: 1 min review, examples-code-changes

#364 fix expression
  docs/downloads/automation-library/integrations/github-actions/dispatch-github-action/dispatch_github_action_branch.cm
Labels: 1 min review, examples-code-changes

#365 Create Repo Stats Tracking Workflow
  .github/workflows/github-repo-stats.yml
Labels: 1 min review

#358 Playground docs
  docs/changelog.md
  docs/gitStream-playground.md
  docs/screenshots/Playground-Overview.png
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: 1 min review, no screenshot

#366 Update mkdocs.yml - Add gitlab docs
  mkdocs.yml
Labels: 1 min review

#369 fix FAQ
  docs/gitlab-installation.md
Labels: 1 min review, no screenshot

#370 Delete github-repo-stats.yml
  .github/workflows/github-repo-stats.yml
Labels: 1 min review
