Repository linear-b/gitstream, pull requests merged in 2023-04, with the labels that each got.

#77 add pr.target and repo.name
  docs/context-variables.md
Labels: 1 min review

#80 support pip plugins
  .github/workflows/deploy.yml
  mkdocs.yml
  requirements.txt
Labels: 1 min review

#82 fix indentation
  .github/workflows/gitstream.yml
  docs/downloads/gitstream.yml
Labels: 1 min review

#88 Update gitStream onboarding sequence
  docs/cm-file.md
  docs/cm-syntax.md
  docs/dry-run-mode.md
  docs/github-installation.md
  docs/how-it-works.md
  docs/quick-start.md
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: do not merge

#110 Update automation rules
  .cm/gitstream.cm
Labels: cm-changes

#112 describe admin rules
  docs/cm-file.md
Labels: 1 min review

#115 added updates section
  README.md
Labels: 1 min review

#114 explain comments in dry run
  docs/dry-run-mode.md
Labels: 1 min review

#118 Change automation to encourage screenshots
  .cm/gitstream.cm
Labels: cm-changes

#120 uninstall instructions details for GitLab
  docs/github-installation.md
  docs/gitlab-installation.md
Labels: 1 min review

#121 Update Safe Changes Example
  automations/approve_safe_changes/README.md
  automations/approve_safe_changes/approve-safe-changes.cm
Labels: 1 min review, examples-code-changes

#123 Approve changes of text files inside docs dir by maintainers
  .cm/gitstream.cm
Labels: cm-changes

#122 Create automation-template.md
  automations/automation-template.md
Labels: 1 min review, no-screenshot

#126 Create change deprecated components example
  automations/change_deprecated_components/README.md
  automations/change_deprecated_components/change_deprecated_components.cm
  automations/change_deprecated_components/change_deprecated_components.png
Labels: 1 min review, examples-code-changes
