Repository linear-b/gitstream, pull requests merged in 2023-05, with the labels that each got.

#128 Minor copyedit
  docs/examples.md
Labels: 1 min review, no-screenshot

#127 Create request_screenshot automation example
  automations/request_screenshot/README.md
  automations/request_screenshot/request-screenshot.png
  automations/request_screenshot/request_screenshot.cm
Labels: 1 min review, examples-code-changes

#129 Create approve_team_by_directory
  automations/approve_team_by_directory/README.md
  automations/approve_team_by_directory/approve_team_by_directory.cm
  automations/approve_team_by_directory/approve_team_by_directory.png
Labels: 1 min review, examples-code-changes

#124 Automations cleanup
  automations/additional_review_for_large_pr/README.md
  automations/additional_review_for_large_pr/additional_review_for_large_pr.cm
  automations/additional_review_for_large_pr/additional_review_for_large_pr.png
  automations/approve_additions_to_tests/README.md
  automations/approve_additions_to_tests/approve-additions-to-tests.cm
  automations/approve_javascript_formatting_change/README.md
  automations/approve_javascript_formatting_change/approve_javascript_formatting_change.cm
  automations/approve_javascript_log_output/README.md
  automations/approve_javascript_log_output/approve_javascript_log_output.cm
  automations/approve_logging_fixes/README.md
  automations/approve_logging_fixes/approve-changes-to-prints.cm
  automations/approve_python_log_output/README.md
  automations/approve_python_log_output/approve_python_log_output.cm
  automations/approve_safe_changes/README.md
  automations/approve_safe_changes/approve-safe-changes.cm
  automations/approve_tests/README.md
  automations/approve_tests/approve_tests.cm
  automations/approve_tests/approve_tests.png
  automations/approve_tiny_changes/README.md
  automations/approve_tiny_changes/approve_tiny_change.png
  automations/approve_tiny_changes/approve_tiny_changes.cm
  automations/assign_code_experts/README.md
  automations/assign_code_experts/assign_code_experts.cm
  automations/assign_code_experts/assign_code_experts.png
  automations/assign_reviewers_by_directory/README.md
  automations/assign_reviewers_by_directory/assign-reviewers-by-directory.cm
  automations/assign_reviewers_by_type_of_change/README.md
  automations/assign_reviewers_by_type_of_change/assign-reviewers-by-type-of-change.cm
  automations/assign_the_right_reviewers/README.md
  automations/assign_the_right_reviewers/assign-the-right-reviewers.cm
  automations/automation-template.md
  automations/check_ticket_for_every_pr/README.md
  automations/label_missing_jira_info/README.md
  automations/label_missing_jira_info/label_missing_jira_info.cm
  automations/label_prs_by_complexity/README.md
  automations/label_prs_without_tests/README.md
  automations/label_prs_without_tests/label_prs_without_tests.cm
  automations/label_prs_without_tests/label_prs_without_tests.png
  automations/mark_prs_without_tests/README.md
  automations/mark_prs_without_tests/removing-missing-labels-example.png
  automations/percent_new_code/README.md
  automations/percent_new_code/percent_new_code.cm
  automations/percent_new_code/percent_new_code.png
  automations/provide_estimated_time_to_review/README.md
  automations/provide_estimated_time_to_review/provide_estimated_time_to_review.cm
  automations/provide_estimated_time_to_review/provide_estimated_time_to_review.png
  automations/require_2_approvals_for_complex_prs/README.md
  automations/validate_formatting_changes_for_js/README.md
Labels: 1 min review, no-screenshot, examples-code-changes

#130 Create assign_reviewers_by_directory.png
  automations/assign_reviewers_by_directory/assign_reviewers_by_directory.png
Labels: 1 min review

#131 Add review_sensitive_files example
  automations/review_sensitive_files/README.md
  automations/review_sensitive_files/review_sensitive_files.cm
  automations/review_sensitive_files/review_sensitive_files.png
Labels: 1 min review, examples-code-changes

#132 Create change_missing_lambda_field
  automations/change_missing_lambda_field/README.md
  automations/change_missing_lambda_field/change_missing_lambda_field.cm
  automations/change_missing_lambda_field/change_missing_lambda_field.png
Labels: 1 min review, examples-code-changes

#133 Create label_deleted_files
  automations/label_deleted_files/README.md
  automations/label_deleted_files/label_deleted_files.cm
  automations/label_deleted_files/label_deleted_files.png
Labels: 1 min review, examples-code-changes

#134 Create welcome_newcomer
  automations/welcome_newcomer/README.md
  automations/welcome_newcomer/welcome_newcomer.cm
  automations/welcome_newcomer/welcome_newcomer.png
Labels: 1 min review, examples-code-changes

#135 Create close_wrong_team_by_directory
  automations/close_wrong_team_by_directory/README.md
  automations/close_wrong_team_by_directory/close_wrong_team_by_directory.cm
  automations/close_wrong_team_by_directory/close_wrong_team_by_directory.png
Labels: 1 min review, examples-code-changes

#137 Add missing short description.
  automations/welcome_newcomer/README.md
Labels: 1 min review, no-screenshot

#136 Fix image link
  automations/change_missing_lambda_field/README.md
Labels: 1 min review, no-screenshot

#140 Update primary landing pages
  README.md
  docs/assets/change-deprecated-highlight.png
  docs/assets/code-experts-highlight.png
  docs/assets/etr-label-highlight.png
  docs/assets/safe-change-highlight.png
  docs/automations/approve-safe-changes/approve-safe-changes.png
  docs/downloads/gitstream.cm
  docs/index.md
Labels: 1 min review, examples-code-changes

#142 Mark no screenshots only when changing presented docs in docs dir
  .cm/gitstream.cm
Labels: cm-changes

#141 Fix docs links.
  README.md
Labels: 1 min review

#139 Add tip to explainCodeExperts
  docs/filter-functions.md
Labels: 1 min review, no screenshot

#147 Create new automation example issue template.
  .github/ISSUE_TEMPLATE/new_automation_example.md
  docs/automations/automation-library.md
Labels: 1 min review, no screenshot

#143 added merged status and open request changes to pr context
  docs/context-variables.md
Labels: 1 min review, no screenshot

#148 Fix install instruction location
  docs/gitlab-installation.md
Labels: 1 min review, no screenshot

#149 local documentation server setup
  README.md
Labels: 1 min review

#151 fix typos
  docs/custom-filters-v1.md
Labels: 1 min review

#152 Basic example
  docs/custom-filters-v1.md
Labels: 1 min review

#154 py formating
  docs/filter-functions.md
Labels: 1 min review, no screenshot

#155 Add reviewer fail on error
  docs/automation-actions.md
Labels: 1 min review, no screenshot

#157 Create approve_python_formatting_change
  docs/automations/approve-python-formatting-change/README.md
  docs/automations/approve-python-formatting-change/approve_python_formatting_change.png
  docs/automations/automation-library.md
  docs/downloads/automation-library/approve_python_formatting_change.cm
Labels: 1 min review, examples-code-changes, no screenshot

#158 Update approve-javascript-formatting-change
  docs/automations/approve-javascript-formatting-change/README.md
  docs/automations/approve-javascript-formatting-change/approve-javascript-formatting-change.png
Labels: 1 min review, no screenshot

#160 Update gitstream.cm
  .cm/gitstream.cm
Labels: cm-changes

#159 Add documentation on how to mix and control global and repo rules
  docs/cm-file.md
Labels: 1 min review

#161 Rename automation title.
  docs/automations/approve-team-by-directory/README.md
Labels: 1 min review, no screenshot

#162 add allImages filter function
  docs/downloads/automation-library/approve-safe-changes.cm
Labels: 1 min review, examples-code-changes

#167 Approve swimm
  docs/automations/approve-swimm/README.md
  docs/automations/approve-swimm/approve-swimm.png
  docs/automations/automation-library.md
  docs/downloads/automation-library/approve_swimm.cm
Labels: 1 min review, examples-code-changes, no screenshot

#168 Fix Swimm URL
  docs/automations/approve-swimm/README.md
Labels: 1 min review, no screenshot

#165 PR context: comments, conversations and reviews
  docs/context-variables.md
  docs/custom-filters-v1.md
Labels: 1 min review

#169 add list indicator
  docs/context-variables.md
Labels: 1 min review

#171 Update gitstream.cm
  .cm/gitstream.cm
Labels: cm-changes

#176 Fix no screenshot logic
  .cm/gitstream.cm
Labels: cm-changes

#175 have each image and text wrapped in single frame
  docs/index.md
Labels: 1 min review

#174 Restructure Integrations Docs
  docs/automations/approve-swimm/README.md
  docs/automations/automation-library.md
  docs/automations/automation-template.md
  docs/automations/integrations/dependabot/approve-dependabot/README.md
  docs/automations/integrations/jira/label-missing-jira-info/README.md
  docs/automations/integrations/jira/label-missing-jira-info/label_missing_jira_info.png
  docs/automations/integrations/swimm/approve-swimm/README.md
  docs/automations/integrations/swimm/approve-swimm/approve-swimm.png
  docs/automations/label-missing-jira-info/README.md
  docs/downloads/automation-library/integrations/dependabot/approve_dependabot.cm
  docs/downloads/automation-library/integrations/jira/label_missing_jira_info.cm
  docs/downloads/automation-library/integrations/swimm/approve_swimm.cm
  docs/examples.md
  docs/index.md
  docs/integrations/README.md
  docs/integrations/dependabot.md
  docs/integrations/jira.md
  docs/integrations/swimm.md
  mkdocs.yml
Labels: 1 min review, examples-code-changes, no screenshot

#172 Minor copyedits to change team names.
  docs/downloads/automation-library/assign_reviewers_by_directory.cm
Labels: 1 min review, examples-code-changes

#178 dark mode background
  docs/stylesheets/extra.css
Labels: 1 min review

#181 fix example that have every after boolean checks
  docs/downloads/automation-library/approve-safe-changes.cm
Labels: 1 min review, examples-code-changes

#180 fix syntax error
  docs/downloads/automation-library/change_deprecated_components.cm
Labels: 1 min review, examples-code-changes

#183 Create SonarCloud Integration Examples
  docs/automations/integrations/sonar/approve-sonar-clean-code/README.md
  docs/automations/integrations/sonar/approve-sonar-clean-code/approve-sonar-clean-code.png
  docs/automations/integrations/sonar/label-sonar/README.md
  docs/automations/integrations/sonar/label-sonar/label-sonar.png
  docs/automations/integrations/sonar/review-sonar-alerts/README.md
  docs/automations/integrations/sonar/review-sonar-alerts/review-sonar-alerts.png
  docs/automations/integrations/sonar/review-sonar-duplications/README.md
  docs/automations/integrations/sonar/review-sonar-duplications/review-sonar-duplications.png
  docs/downloads/automation-library/integrations/sonar/approve_sonar_clean_code.cm
  docs/downloads/automation-library/integrations/sonar/label_sonar.cm
  docs/downloads/automation-library/integrations/sonar/review_sonar_alerts.cm
  docs/downloads/automation-library/integrations/sonar/review_sonar_duplications.cm
  docs/integrations/README.md
  docs/integrations/sonar.md
Labels: examples-code-changes, no screenshot, 10 min review

#184 Update review-sonar-duplications.png
  docs/automations/integrations/sonar/review-sonar-duplications/review-sonar-duplications.png
Labels: 1 min review

#182 added jit filter doc
  docs/context-variables.md
  docs/filter-functions.md
Labels: 5 min review

#190 Add missing sonar custom expression
  docs/downloads/automation-library/integrations/sonar/review_sonar_alerts.cm
Labels: 1 min review, examples-code-changes

#189 Map to enum documentation
  docs/filter-functions.md
Labels: 1 min review

#193 added filters to reserved words and rearrange
  docs/how-it-works.md
Labels: 1 min review
