Repository linear-b/gitstream, pull requests merged in 2023-07, with the labels that each got.

#224 action explain-code-experts
  docs/automation-actions.md
  docs/filter-functions.md
Labels: 1 min review

#225 typo fix
  docs/automation-actions.md
Labels: 1 min review

#229 add context to pr: unresolved_threads
  docs/context-variables.md
Labels: 1 min review

#230 fix CM syntax error
  docs/downloads/automation-library/assign_code_experts.cm
  docs/downloads/gitstream.cm
Labels: 1 min review, examples-code-changes

#222 add round
  docs/downloads/automation-library/percent_new_code.cm
Labels: 1 min review, examples-code-changes

#231 Fix typo in colors custom expression example
  docs/downloads/automation-library/utilities/colors_custom_expression.cm
Labels: 1 min review, examples-code-changes

#232 point to the CM syntax definitions for ST4
  docs/faq.md
Labels: 1 min review

#234 Create explain code experts automation example and update Assign code experts and quickstart examples.
  docs/automations/automation-library.md
  docs/automations/standard/explain-code-experts/README.md
  docs/automations/standard/explain-code-experts/explain-code-experts.png
  docs/downloads/automation-library/assign_code_experts.cm
  docs/downloads/automation-library/standard/explain_code_experts.cm
  docs/downloads/gitstream.cm
  docs/quick-start.md
Labels: 5 min review, examples-code-changes

#237 trigger on comments
  docs/execution-model.md
Labels: 1 min review

#238 Fix screenshot match rules with one more link type
  .cm/gitstream.cm
Labels: cm-changes

#239 improve includes filter input desc
  docs/filter-functions.md
Labels: 1 min review

#245 added author_is_org_member
  docs/context-variables.md
Labels: 1 min review

#243 Create Javadoc integration content.
  docs/automations/integrations/javadoc/review-javadoc-input-parameters/README.md
  docs/automations/integrations/javadoc/review-javadoc-input-parameters/review-javadoc-input-parameters.png
  docs/automations/integrations/javadoc/review-javadoc-large-change/README.md
  docs/automations/integrations/javadoc/review-javadoc-large-change/review-javadoc-large-change.png
  docs/automations/integrations/javadoc/review-javadoc/README.md
  docs/automations/integrations/javadoc/review-javadoc/review-javadoc.png
  docs/automations/integrations/javadoc/review-new-class-javadoc/README.md
  docs/automations/integrations/javadoc/review-new-class-javadoc/review-new-class-javadoc.png
  docs/downloads/automation-library/integrations/javadoc/review_javadoc_changes.cm
  docs/downloads/automation-library/integrations/javadoc/review_javadoc_input_parameters.cm
  docs/downloads/automation-library/integrations/javadoc/review_javadoc_large_change.cm
  docs/downloads/automation-library/integrations/javadoc/review_new_class_javadoc.cm
  docs/integrations/README.md
  docs/integrations/javadoc.md
Labels: examples-code-changes, 10 min review

#246 support explain-code-experts for gitlab
  docs/automation-actions.md
Labels: 1 min review

#247 Reorganize home page
  docs/index.md
Labels: 1 min review, no screenshot

#252 Create JSDoc Integration
  docs/automations/integrations/jsdoc/review-jsdoc-input/README.md
  docs/automations/integrations/jsdoc/review-jsdoc-input/review-jsdoc-input.png
  docs/automations/integrations/jsdoc/review-jsdoc-large/README.md
  docs/automations/integrations/jsdoc/review-jsdoc-large/review-jsdoc-large.png
  docs/automations/integrations/jsdoc/review-jsdoc-new-class/README.md
  docs/automations/integrations/jsdoc/review-jsdoc-new-class/review-jsdoc-new-class.png
  docs/automations/integrations/jsdoc/review-jsdoc/README.md
  docs/automations/integrations/jsdoc/review-jsdoc/review-jsdoc.png
  docs/downloads/automation-library/integrations/jsdoc/review_jsdoc.cm
  docs/downloads/automation-library/integrations/jsdoc/review_jsdoc_input.cm
  docs/downloads/automation-library/integrations/jsdoc/review_jsdoc_large.cm
  docs/downloads/automation-library/integrations/jsdoc/review_jsdoc_new_class.cm
  docs/integrations/README.md
  docs/integrations/jsdoc.md
Labels: examples-code-changes, 10 min review

#257 Fix SEO Issues
  docs/automation-actions.md
  docs/cm-file.md
  docs/context-variables.md
  docs/dry-run-mode.md
  docs/examples.md
  docs/faq.md
  docs/filter-functions.md
  docs/github-installation.md
  docs/gitlab-installation.md
  docs/how-it-works.md
  docs/index.md
  docs/integrations/dependabot.md
  docs/integrations/javadoc.md
  docs/integrations/jira.md
  docs/integrations/jit.md
  docs/integrations/jsdoc.md
  docs/integrations/sonar.md
  docs/integrations/swimm.md
  docs/quick-start.md
  docs/troubleshooting.md
Labels: no screenshot, 10 min review

#258 meta descriptions galore
  docs/automations/additional-review-for-large-pr/README.md
  docs/automations/approve-javascript-formatting-change/README.md
  docs/automations/approve-javascript-log-output/README.md
  docs/automations/approve-python-formatting-change/README.md
  docs/automations/approve-python-log-output/README.md
  docs/automations/approve-safe-changes/README.md
  docs/automations/approve-team-by-directory/README.md
  docs/automations/approve-tests/README.md
  docs/automations/approve-tiny-changes/README.md
  docs/automations/assign-code-experts/README.md
  docs/automations/assign-reviewers-by-directory/README.md
  docs/automations/assign-team-members-as-reviewers/README.md
  docs/automations/automation-template.md
  docs/automations/change-deprecated-components/README.md
  docs/automations/change-missing-lambda-field/README.md
  docs/automations/close-wrong-team-by-directory/README.md
  docs/automations/integrations/dependabot/approve-dependabot/README.md
  docs/automations/integrations/javadoc/review-javadoc-input-parameters/README.md
  docs/automations/integrations/javadoc/review-javadoc-large-change/README.md
  docs/automations/integrations/javadoc/review-javadoc/README.md
  docs/automations/integrations/javadoc/review-new-class-javadoc/README.md
  docs/automations/integrations/jira/label-missing-jira-info/README.md
  docs/automations/integrations/jit/label-jit-alerts/README.md
  docs/automations/integrations/jit/review-jit-alerts/README.md
  docs/automations/integrations/jit/review-jit-ignore-accept/README.md
  docs/automations/integrations/jit/review-jit-secret/README.md
  docs/automations/integrations/jsdoc/review-jsdoc-input/README.md
  docs/automations/integrations/jsdoc/review-jsdoc-large/README.md
  docs/automations/integrations/jsdoc/review-jsdoc-new-class/README.md
  docs/automations/integrations/jsdoc/review-jsdoc/README.md
  docs/automations/integrations/sonar/approve-sonar-clean-code/README.md
  docs/automations/integrations/sonar/label-sonar/README.md
  docs/automations/integrations/sonar/review-sonar-alerts/README.md
  docs/automations/integrations/sonar/review-sonar-duplications/README.md
  docs/automations/integrations/swimm/approve-swimm/README.md
  docs/automations/label-deleted-files/README.md
  docs/automations/label-prs-without-tests/README.md
  docs/automations/percent-new-code/README.md
  docs/automations/provide-estimated-time-to-review/README.md
  docs/automations/request-screenshot/README.md
  docs/automations/review-sensitive-files/README.md
  docs/automations/standard/explain-code-experts/README.md
  docs/automations/standard/review-changelog/README.md
  docs/automations/standard/share-knowledge/README.md
  docs/automations/welcome-newcomer/README.md
  docs/integrations/dependabot.md
  docs/integrations/javadoc.md
  docs/integrations/jira.md
  docs/integrations/jit.md
  docs/integrations/jsdoc.md
  docs/integrations/sonar.md
  docs/integrations/swimm.md
Labels: 20 min review

#256 Add Integrations to automation library.
  docs/automations/automation-library.md
  docs/integrations/README.md
Labels: 1 min review

#251 remove comment filter
  docs/downloads/code-experts.cm
  docs/filter-functions.md
Labels: examples-code-changes

#263 Fix Integrations page URLs for embedding
  docs/integrations/README.md
Labels: no screenshot
