Repository linear-b/gitstream, pull requests merged in 2023-06, with the labels that each got.

#195 explain how to use branch.diff.files_metadata
  docs/context-variables.md
Labels: 1 min review

#199 added mention for unsupported by gitlab
  docs/filter-functions.md
  docs/index.md
Labels: 1 min review

#198 fix typo in Additional Review for Large PRs
  docs/automations/additional-review-for-large-pr/README.md
Labels: 1 min review, no screenshot

#202 typo fix
  docs/how-it-works.md
Labels: 1 min review

#203 Assorted Improvements
  automations/welcome_newcomer/README.md
  docs/automations/additional-review-for-large-pr/README.md
  docs/automations/approve-javascript-formatting-change/README.md
  docs/automations/approve-python-formatting-change/README.md
  docs/automations/approve-safe-changes/README.md
  docs/automations/approve-team-by-directory/README.md
  docs/automations/approve-tests/README.md
  docs/automations/approve-tiny-changes/README.md
  docs/automations/assign-code-experts/README.md
  docs/automations/assign-reviewers-by-directory/README.md
  docs/automations/automation-library.md
  docs/automations/automation-template.md
  docs/automations/change-deprecated-components/README.md
  docs/automations/change-missing-lambda-field/README.md
  docs/automations/close-wrong-team-by-directory/README.md
  docs/automations/integrations/jira/label-missing-jira-info/README.md
  docs/automations/integrations/sonar/approve-sonar-clean-code/README.md
  docs/automations/integrations/sonar/label-sonar/README.md
  docs/automations/integrations/sonar/review-sonar-alerts/README.md
  docs/automations/integrations/sonar/review-sonar-duplications/README.md
  docs/automations/integrations/swimm/approve-swimm/README.md
  docs/automations/label-deleted-files/README.md
  docs/automations/label-prs-without-tests/README.md
  docs/automations/percent-new-code/README.md
  docs/automations/provide-estimated-time-to-review/README.md
  docs/automations/request-screenshot/README.md
  docs/automations/review-sensitive-files/README.md
  docs/automations/utilities/cm-header/README.md
  docs/automations/utilities/colors-custom-expression/README.md
  docs/automations/welcome-newcomer/README.md
  docs/downloads/automation-library/change_deprecated_components.cm
  docs/downloads/automation-library/provide_estimated_time_to_review.cm
  docs/downloads/automation-library/utilities/cm_header.cm
  docs/downloads/automation-library/utilities/colors_custom_expression.cm
  docs/gitlab-installation.md
  docs/how-it-works.md
  docs/screenshots/gitstream-ui.png
  docs/stylesheets/extra.css
Labels: examples-code-changes, no screenshot, 20 min review

#201 Checks in PR context released
  docs/context-variables.md
Labels: 1 min review

#206 explain ignore files
  docs/cm-file.md
Labels: 1 min review

#204 Jit examples
  docs/automations/automation-template.md
  docs/automations/integrations/jit/label-jit-alerts/README.md
  docs/automations/integrations/jit/label-jit-alerts/label-jit-alerts.png
  docs/automations/integrations/jit/review-jit-alerts/README.md
  docs/automations/integrations/jit/review-jit-alerts/review-jit-alerts.png
  docs/automations/integrations/jit/review-jit-ignore-accept/README.md
  docs/automations/integrations/jit/review-jit-ignore-accept/review-jit-ignore-accept.png
  docs/automations/integrations/jit/review-jit-secret/README.md
  docs/automations/integrations/jit/review-jit-secret/review-jit-secret.png
  docs/downloads/automation-library/integrations/jit/label_jit_alerts.cm
  docs/downloads/automation-library/integrations/jit/review_jit_alerts.cm
  docs/downloads/automation-library/integrations/jit/review_jit_ignore_accept.cm
  docs/downloads/automation-library/integrations/jit/review_jit_secret.cm
  docs/integrations/README.md
  docs/integrations/jit.md
Labels: examples-code-changes, no screenshot, 10 min review

#211 Gitlab install changes
  docs/gitlab-installation.md
  docs/index.md
  mkdocs.yml
Labels: 1 min review

#212 fix indentation in additional_review_for_large_pr
  docs/downloads/automation-library/additional_review_for_large_pr.cm
Labels: 1 min review, examples-code-changes

#213 create review css important automation
  docs/automations/automation-library.md
  docs/automations/languages/css/review-css-important/README.md
  docs/automations/languages/css/review-css-important/review-css-important.png
  docs/downloads/automation-library/languages/css/review_css_important.cm
Labels: 5 min review, examples-code-changes, no screenshot

#219 Add Integrations link to Readme usage section.
  README.md
Labels: 1 min review

#221 fix regex in label_missing_jira_info.cm
  docs/downloads/automation-library/integrations/jira/label_missing_jira_info.cm
Labels: 1 min review, examples-code-changes
