Repository linear-b/gitstream, pull requests merged in 2024-05, with the labels that each got.

#494 add github indication for wati fora all checks
  docs/automation-actions.md
Labels: 1 min review

#492 Update how-it-works.md
  docs/how-it-works.md
Labels: 1 min review, no screenshot

#495 Fix TODO cm so it will show a comment only for newly added TODO
  docs/downloads/automation-library/standard/review-todo-comments/review_todo_comments.cm
Labels: 1 min review, examples-code-changes, 1 Unresolved Thread(s)

#496 New Jira Integration Examples
  docs/automations/integrations/jira/configure/README.md
  docs/automations/integrations/jira/create-jira-issue/README.md
  docs/automations/integrations/jira/create-jira-issue/create-jira-issue-github.png
  docs/automations/integrations/jira/create-jira-issue/create-jira-issue-jira.png
  docs/automations/integrations/jira/create-jira-ticket/README.md
  docs/automations/integrations/jira/create-jira-ticket/create-jira-ticket.png
  docs/automations/integrations/jira/jira-assign/README.md
  docs/automations/integrations/jira/jira-assign/jira-assign-github.png
  docs/automations/integrations/jira/jira-assign/jira-assign-jira.png
  docs/automations/integrations/jira/jira-change-status/README.md
  docs/automations/integrations/jira/jira-change-status/jira-change-status-github.png
  docs/automations/integrations/jira/jira-change-status/jira-change-status-jira.png
  docs/automations/integrations/jira/jira-update-field/README.md
  docs/automations/integrations/jira/jira-update-field/jira-update-field-github.png
  docs/automations/integrations/jira/jira-update-field/jira-update-field-jira.png
  docs/downloads/automation-library/assign_reviewers_by_directory.cm
  docs/downloads/automation-library/create_jira_ticket.cm
  docs/downloads/automation-library/integrations/jira/create_jira_issue.cm
  docs/downloads/automation-library/integrations/jira/jira_assign.cm
  docs/downloads/automation-library/integrations/jira/jira_change_status.cm
  docs/downloads/automation-library/integrations/jira/jira_update_field.cm
  docs/downloads/images/integrations/jira/jira-change-status.png
  docs/downloads/images/integrations/jira/jira-comment-1.png
  docs/downloads/images/integrations/jira/jira-comment-2.png
  docs/downloads/images/integrations/jira/jira-comment-3.png
  docs/downloads/images/integrations/jira/jira-pre-1.png
  docs/filter-function-plugins.md
  docs/integrations/jira.md
  docs/integrations/jira/README.md
  docs/integrations/jira/jira-webhook-automation.png
  plugins/filters/hasJiraIssue/LICENSE
  plugins/filters/hasJiraIssue/README.md
  plugins/filters/hasJiraIssue/has_jira_issue.cm
  plugins/filters/hasJiraIssue/index.js
  plugins/filters/hasJiraIssue/reference.md
  plugins/filters/hasJiraTicket/README.md
  plugins/filters/hasJiraTicket/index.js
Labels: examples-code-changes, 20 min review

#497 Fix typo in Jira automation header
  docs/integrations/jira/README.md
Labels: 1 min review, no screenshot

#498 triggers config
  docs/changelog.md
  docs/cm-file.md
  docs/execution-model.md
Labels: 5 min review

#500 reverse order of dependabot use cases to show risk aware first
  docs/automations/integrations/dependabot/approve-dependabot/README.md
Labels: 1 min review

#502 fix typo in example
  docs/execution-model.md
Labels: 1 min review

#504 update category field metadata
  docs/automations/approve-tests/README.md
  docs/automations/integrations/asana/link-asana/README.md
  docs/automations/integrations/azure-boards/label-missing-azure-boards/README.md
  docs/automations/integrations/azure-boards/link-azure-boards/README.md
  docs/automations/integrations/copilot/flag-copilot-pr/README.md
  docs/automations/integrations/dependabot/approve-dependabot/README.md
  docs/automations/integrations/devcycle/label-ff-devcycle/README.md
  docs/automations/integrations/flagr/label-ff-flagr/README.md
  docs/automations/integrations/flagsmith/label-ff-flagsmith/README.md
  docs/automations/integrations/github-actions/dispatch-github-action/README.md
  docs/automations/integrations/github-actions/skip-github-action/README.md
  docs/automations/integrations/jira/create-jira-issue/README.md
  docs/automations/integrations/jira/create-jira-ticket/README.md
  docs/automations/integrations/jira/jira-change-status/README.md
  docs/automations/integrations/jira/label-missing-jira-info/README.md
  docs/automations/integrations/jira/link-jira/README.md
  docs/automations/integrations/orca/review-orca-alerts/README.md
  docs/automations/integrations/rdoc/review-rdoc-input/README.md
  docs/automations/integrations/rdoc/review-rdoc-large/README.md
  docs/automations/integrations/rdoc/review-rdoc-new-class/README.md
  docs/automations/integrations/rdoc/review-rdoc/README.md
  docs/automations/integrations/renovate/approve-renovate/README.md
  docs/automations/integrations/shortcut/label-missing-shortcut/README.md
  docs/automations/integrations/shortcut/link-shortcut/README.md
  docs/automations/integrations/slack/slack-send-notification/README.md
  docs/automations/integrations/snyk/approve-snyk/README.md
  docs/automations/integrations/sonar/approve-sonar-clean-code/README.md
  docs/automations/integrations/sonar/label-sonar/README.md
  docs/automations/integrations/swimm/approve-swimm/README.md
  docs/automations/integrations/teams/teams-send-notification/README.md
  docs/automations/integrations/terraform/review-new-module/README.md
  docs/automations/integrations/terraform/review-terraform-module-name/README.md
  docs/automations/integrations/terraform/review-terraform-source-version/README.md
  docs/automations/integrations/terraform/review-terraform/README.md
  docs/automations/label-deleted-files/README.md
  docs/automations/languages/golang/approve-golang-log-output/README.md
  docs/automations/languages/golang/review-missing-golang-tests/README.md
  docs/automations/languages/html/enforce-html-title-length/README.md
  docs/automations/languages/html/enforce-image-alt/README.md
  docs/automations/languages/html/flag-duplicate-h1/README.md
  docs/automations/languages/html/flag-missing-html-tags/README.md
  docs/automations/languages/html/review-css-important/README.md
  docs/automations/languages/java/approve-java-log-output/README.md
  docs/automations/languages/java/review-java-test-name/README.md
  docs/automations/languages/java/review-missing-java-tests/README.md
  docs/automations/languages/python/review-missing-python-tests/README.md
  docs/automations/languages/python/review-python-test-name/README.md
  docs/automations/languages/ruby/approve-ruby-log-output/README.md
  docs/automations/languages/ruby/review-missing-ruby-tests/README.md
  docs/automations/languages/ruby/review-ruby-test-name/README.md
  docs/automations/languages/rust/approve-rust-log-output/README.md
  docs/automations/percent-new-code/README.md
  docs/automations/provide-estimated-time-to-review/README.md
  docs/automations/standard/branch-management/enforce-branch-name/README.md
  docs/automations/standard/enforce-copyright-header/README.md
  docs/automations/standard/explain-code-experts/README.md
  docs/automations/standard/label-management/label-unresolved-threads/README.md
  docs/automations/standard/link-issue-tracker/README.md
  docs/automations/welcome-newcomer/README.md
Labels: 30 min review, no screenshot

#506 Add dev team as a reviewers to docs
  .cm/notify-dev-team.cm
Labels: cm-changes

#507 final version for release
  docs/execution-model.md
Labels: 1 min review

#509 added lock files list and cleaned lagging white spaces
  docs/filter-functions.md
Labels: 1 min review

#508 Update execution-model.md
  docs/execution-model.md
Labels: 1 min review

#510 fix wrong indentation
  docs/automations/assign-team-members-as-reviewers/README.md
  docs/automations/integrations/jira/configure/README.md
  docs/automations/languages/html/README.md
  docs/downloads/automation-library/integrations/github-actions/skip-github-action/skip_github_action_branch.cm
  docs/downloads/automation-library/integrations/github-actions/skip-github-action/skip_github_action_label.cm
  docs/downloads/automation-library/integrations/github-actions/skip-github-action/skip_github_action_resource.cm
  docs/downloads/automation-library/integrations/slack/slack_send_notification.cm
  docs/downloads/automation-library/integrations/zapier/zapier_export_pr_reviewers.cm
  docs/downloads/automation-library/standard/review-assignment/notify_watcher.cm
Labels: 5 min review, examples-code-changes, no screenshot

#512 Triggers docs improvements
  docs/cm-file.md
  docs/execution-model.md
Labels: 5 min review

#513 fix markdown
  docs/execution-model.md
Labels: 1 min review

#515 Remove unecessary trigger condition from jira example
  docs/downloads/automation-library/integrations/jira/jira_update_field.cm
Labels: 1 min review, examples-code-changes

#517 remove gitlab single repo
  docs/gitlab-installation.md
Labels: 1 min review

#518 Update gitlab-installation.md
  docs/gitlab-installation.md
Labels: 1 min review, no screenshot

#520 update to GH action to v2
  docs/downloads/gitstream.yml
  docs/github-installation.md
  docs/how-it-works.md
  docs/troubleshooting.md
  plugins/filters/getCodeowners/README.md
  tutorials/basic-usage-python-repo/.github/workflows/gitstream.yml
Labels: 5 min review, no screenshot

#519 Simplified GitLab workflow
  docs/changelog.md
  docs/downloads/gitlab-ci.yml
Labels: 1 min review

#523 Removed docker from GitHub installation
  docs/github-installation.md
Labels: 1 min review
