Repository linear-b/gitstream, pull requests merged in 2024-09, with the labels that each got.

#575 added rule to describe pr
  .cm/ask-ai.cm
  docs/filter-functions.md
Labels: cm-changes

#571 LINBEE-9831 -Ask ai plugin
  docs/filter-function-plugins.md
  docs/screenshots/askAI-describe-PR.png
  docs/screenshots/askAI-qa.png
  plugins/filters/askAI/LICENSE
  plugins/filters/askAI/README.md
  plugins/filters/askAI/askAI.cm
  plugins/filters/askAI/index.js
  plugins/filters/askAI/reference.md
  plugins/filters/hasJiraIssue/reference.md
Labels: examples-code-changes, 10 min review, suggest-ticket

#579 Update ask-ai.cm
  .cm/ask-ai.cm
Labels: cm-changes

#578 Add AI usage examples
  docs/automations/automation-library.md
  docs/automations/integrations/AI/README.md
  docs/automations/integrations/AI/askAI/README.md
  docs/downloads/automation-library/integrations/askAI/askAI_CR.cm
  docs/downloads/automation-library/integrations/askAI/askAI_QA.cm
  docs/downloads/automation-library/integrations/askAI/askAI_describe.cm
  docs/filter-function-plugins.md
  docs/integrations/README.md
Labels: 5 min review, examples-code-changes

#580 add PavelLinearB to admins
  .cm/gitstream.cm
Labels: cm-changes

#581 fix github-installation.md to display images
  docs/github-installation.md
Labels: 1 min review

#582 fixed link in automations/README.md
  automations/README.md
Labels: 1 min review

#583 Fix formatting issues on label-management & branch-management pages
  docs/automations/standard/branch-management/README.md
  docs/automations/standard/branch-management/enforce-branch-name/README.md
  docs/automations/standard/label-management/README.md
  docs/automations/standard/label-management/enforce-labels/README.md
  docs/automations/standard/label-management/label-approvals/README.md
  docs/automations/standard/label-management/label-modified-resources/README.md
  docs/automations/standard/label-management/label-prs-by-language/README.md
  docs/automations/standard/label-management/label-resources-percent/README.md
  docs/automations/standard/label-management/label-unresolved-threads/README.md
  docs/automations/standard/label-management/suggest-labels/README.md
Labels: 1 min review

#585 Update ask-ai.cm
  .cm/ask-ai.cm
Labels: cm-changes

#587 Update ask-ai.cm
  .cm/ask-ai.cm
Labels: cm-changes

#586 AskAI improvements
  docs/automations/integrations/AI/README.md
  docs/automations/integrations/AI/askAI/README.md
  docs/automations/integrations/askAI/README.md
  docs/automations/integrations/askAI/add-tests/README.md
  docs/automations/integrations/askAI/code-review/README.md
  docs/automations/integrations/askAI/summarize-pr/README.md
  docs/automations/integrations/askAI/summarize-pr/summarized-pr.png
  docs/downloads/automation-library/integrations/askAI/askAI_CR.cm
  docs/downloads/automation-library/integrations/askAI/askAI_QA.cm
  docs/downloads/automation-library/integrations/askAI/askAI_describe.cm
  docs/downloads/automation-library/integrations/askAI/askAI_summarize.cm
  docs/downloads/automation-library/integrations/askAI/askAI_tests.cm
  docs/integrations/README.md
Labels: examples-code-changes, 10 min review

#589 Update ask-ai.cm
  .cm/ask-ai.cm
Labels: cm-changes

#590 add linebreake
  .cm/ask-ai.cm
Labels: cm-changes

#588 added role to askAI plugin + examples
  docs/downloads/automation-library/integrations/askAI/askAI_CR.cm
  docs/downloads/automation-library/integrations/askAI/askAI_summarize.cm
  docs/downloads/automation-library/integrations/askAI/askAI_tests.cm
  plugins/filters/askAI/askAI.cm
  plugins/filters/askAI/index.js
  plugins/filters/askAI/reference.md
Labels: 5 min review, examples-code-changes

#591 Context variable fixes
  docs/context-variables.md
Labels: 1 min review

#584 Fix Branched-Based Review Policies Doc
  docs/automations/standard/branch-management/README.md
  docs/downloads/automation-library/standard/review-assignment/review_source_branch.cm
  docs/downloads/automation-library/standard/review-assignment/review_target_branch.cm
Labels: 1 min review, examples-code-changes, no screenshot

#592 added configurtion to label by code comment
  docs/automations/integrations/copilot/flag-copilot-pr/README.md
  docs/automations/integrations/copilot/flag-copilot-pr/label-copilot-comment.png
  docs/downloads/automation-library/integrations/copilot/label_copilot_by_comment.cm
Labels: 1 min review, examples-code-changes

#593 ERT explanation
  docs/filter-functions.md
Labels: 1 min review

#594 Update filter-functions.md
  docs/filter-functions.md
Labels: 1 min review

#595 Fix formatting in cm files
  docs/downloads/javascript.cm
  docs/downloads/organization.cm
  docs/downloads/python.cm
Labels: 1 min review, examples-code-changes
