Repository linear-b/gitstream, pull requests merged in 2024-01, with the labels that each got.

#400 move the playground access into the playground page
  docs/gitStream-playground.md
  mkdocs.yml
Labels: 1 min review

#405 fix sonar labels format
  docs/automations/integrations/sonar/label-sonar/label-sonar.png
  docs/downloads/automation-library/integrations/sonar/label_sonar.cm
Labels: 1 min review, examples-code-changes

#394 Create sales_demo.cm
  docs/downloads/sales_demo.cm
Labels: 1 min review, examples-code-changes

#406 Create isFlaggedUser plugin and new publishing materials for gitStream plugins.
  docs/custom-filters.md
  docs/plugins.md
  docs/snippets/partials/body.hbs
  docs/snippets/partials/sig-name.hbs
  docs/templates/filter-readme-template.md
  mkdocs.yml
  plugins/filters/isFlaggedUser/LICENSE
  plugins/filters/isFlaggedUser/README.md
  plugins/filters/isFlaggedUser/index.js
  plugins/filters/isFlaggedUser/is_flagged_user.cm
  plugins/filters/isFlaggedUser/reference.md
Labels: 5 min review, examples-code-changes

#408 Move LinearB to the top of the Integrations page
  docs/integrations/README.md
Labels: 1 min review, no screenshot

#409 Revamped Filter Function Plugin Content
  docs/custom-filters.md
  docs/downloads/images/gitstream-staging-config.png
  docs/filter-function-plugins.md
  docs/plugins.md
  docs/templates/filter-readme-template.md
  mkdocs.yml
  plugins/filters/banana/README.md
  plugins/filters/banana/index.js
  plugins/filters/isFlaggedUser/index.js
Labels: 5 min review

#385 Added folder for plugins
  docs/filter-function-plugins.md
  plugins/filters/compareSemver/LICENSE
  plugins/filters/compareSemver/README.md
  plugins/filters/compareSemver/compare_semver.cm
  plugins/filters/compareSemver/index.js
  plugins/filters/compareSemver/reference.md
  plugins/filters/extarctDependabotVersionBump/LICENSE
  plugins/filters/extarctDependabotVersionBump/README.md
  plugins/filters/extarctDependabotVersionBump/extarct_dependabot_version_bump.cm
  plugins/filters/extarctDependabotVersionBump/index.js
  plugins/filters/extarctDependabotVersionBump/reference.md
  plugins/filters/extarctSnykVersionBump/LICENSE
  plugins/filters/extarctSnykVersionBump/README.md
  plugins/filters/extarctSnykVersionBump/extarct_snyk_version_bump.cm
  plugins/filters/extarctSnykVersionBump/index.js
  plugins/filters/extarctSnykVersionBump/reference.md
  plugins/filters/extractOrcaFindings/LICENSE
  plugins/filters/extractOrcaFindings/README.md
  plugins/filters/extractOrcaFindings/extarct_orca_findings.cm
  plugins/filters/extractOrcaFindings/index.js
  plugins/filters/extractOrcaFindings/reference.md
  plugins/filters/getCodeowners/LICENSE
  plugins/filters/getCodeowners/README.md
  plugins/filters/getCodeowners/get_codeowners.cm
  plugins/filters/getCodeowners/ignore/LICENSE-MIT
  plugins/filters/getCodeowners/ignore/index.js
  plugins/filters/getCodeowners/index.js
  plugins/filters/getCodeowners/reference.md
Labels: 30 min review, examples-code-changes

#412 fixed typo extract to extract in file names
  docs/filter-function-plugins.md
  plugins/filters/extarctDependabotVersionBump/README.md
  plugins/filters/extarctSnykVersionBump/README.md
  plugins/filters/extractDependabotVersionBump/LICENSE
  plugins/filters/extractDependabotVersionBump/README.md
  plugins/filters/extractDependabotVersionBump/extract_dependabot_version_bump.cm
  plugins/filters/extractDependabotVersionBump/index.js
  plugins/filters/extractDependabotVersionBump/reference.md
  plugins/filters/extractOrcaFindings/README.md
  plugins/filters/extractOrcaFindings/extract_orca_findings.cm
  plugins/filters/extractSnykVersionBump/LICENSE
  plugins/filters/extractSnykVersionBump/README.md
  plugins/filters/extractSnykVersionBump/extract_snyk_version_bump.cm
  plugins/filters/extractSnykVersionBump/index.js
  plugins/filters/extractSnykVersionBump/reference.md
Labels: 5 min review, examples-code-changes, no screenshot

#414 fix wrong url
  docs/filter-function-plugins.md
Labels: 1 min review, no screenshot

#413 fix order of lines
  plugins/filters/extractOrcaFindings/README.md
Labels: 1 min review

#415 FAQ typo fix
  docs/faq.md
Labels: 1 min review, no screenshot

#421 Built in functions
  docs/how-it-works.md
Labels: 1 min review

#420 Remove dead links
  docs/automations/automation-library.md
Labels: 1 min review, no screenshot

#422 change linearb Integration link to fully-qualified filepath
  docs/integrations/README.md
Labels: 1 min review, no screenshot

#425 Add integrations header to automation library page
  docs/automations/automation-library.md
Labels: 1 min review, no screenshot

#419 Feature Flag Integrations
  docs/automations/integrations/devcycle/label-ff-devcycle/README.md
  docs/automations/integrations/devcycle/label-ff-devcycle/label-ff-devcycle.png
  docs/automations/integrations/flagr/label-ff-flagr/README.md
  docs/automations/integrations/flagr/label-ff-flagr/label-ff-flagr.png
  docs/automations/integrations/flagsmith/label-ff-flagsmith/README.md
  docs/automations/integrations/flagsmith/label-ff-flagsmith/label-ff-flagsmith.png
  docs/automations/integrations/launch-darkly/label-ff-launch-darkly/README.md
  docs/automations/integrations/launch-darkly/label-ff-launch-darkly/label-ff-launch-darkly.png
  docs/automations/integrations/unleash/label-ff-unleash/README.md
  docs/automations/integrations/unleash/label-ff-unleash/label-ff-unleash.png
  docs/downloads/automation-library/integrations/devcycle/label-ff-devcycle/label_ff_devcycle.cm
  docs/downloads/automation-library/integrations/flagr/label-ff-flagr/label_ff_flagr.cm
  docs/downloads/automation-library/integrations/flagsmith/label-ff-flagsmith/label_ff_flagsmith.cm
  docs/downloads/automation-library/integrations/launch-darkly/label-ff-launch-darkly/label_ff_launch_darkly.cm
  docs/downloads/automation-library/integrations/unleash/label-ff-unleash/label_ff_unleash.cm
  docs/integrations/README.md
  docs/integrations/devcycle.md
  docs/integrations/flagr.md
  docs/integrations/flagsmith.md
  docs/integrations/launch-darkly.md
  docs/integrations/unleash.md
Labels: examples-code-changes, 10 min review

#426 Create Orca Security integration page
  docs/automations/integrations/orca/label-orca-scan-results/README.md
  docs/automations/integrations/orca/label-orca-scan-results/label-orca-scan-results.png
  docs/downloads/automation-library/integrations/orca/label_orca_scan_results.cm
  docs/downloads/images/orca-logo-dark-mode.png
  docs/downloads/images/orca-logo-light-mode.png
  docs/integrations/README.md
  docs/integrations/orca-security.md
  docs/stylesheets/extra.css
Labels: 5 min review, examples-code-changes

#427 Revert Orca logo
  docs/integrations/README.md
Labels: 1 min review, no screenshot

#428 changed the orca findings screenshot to show secrets and dark mode
  docs/automations/integrations/orca/label-orca-scan-results/README.md
  docs/automations/integrations/orca/label-orca-scan-results/label-orca-scan-results-dark.png
  docs/automations/integrations/orca/label-orca-scan-results/label-orca-scan-results.png
Labels: 1 min review

#431 Snyk and Renovate integration pages and improvements to Dependabot integration
  docs/automations/integrations/dependabot/approve-dependabot/README.md
  docs/automations/integrations/renovate/approve-renovate/README.md
  docs/automations/integrations/renovate/approve-renovate/approve-renovate.png
  docs/automations/integrations/snyk/approve-snyk/README.md
  docs/automations/integrations/snyk/approve-snyk/approve-snyk.png
  docs/downloads/automation-library/integrations/dependabot/approve_dependabot_minor.cm
  docs/downloads/automation-library/integrations/renovate/approve-renovate/approve_renovate.cm
  docs/downloads/automation-library/integrations/snyk/approve-snyk/approve_snyk.cm
  docs/integrations/README.md
  docs/integrations/dependabot.md
  docs/integrations/renovate.md
  docs/integrations/snyk.md
Labels: examples-code-changes, 10 min review

#434 Fix dependabot page
  docs/automations/integrations/dependabot/approve-dependabot/README.md
Labels: 1 min review

#436 Zapier integration Page
  docs/automations/integrations/slack/slack-auto-recognition/README.md
  docs/automations/integrations/slack/slack-auto-recognition/slack-auto-recognition.png
  docs/automations/integrations/slack/slack-send-notification/README.md
  docs/automations/integrations/slack/slack-send-notification/slack-send-notification.png
  docs/automations/integrations/zapier/zapier-export-pr-description-title-url/README.md
  docs/automations/integrations/zapier/zapier-export-pr-number-title-url/README.md
  docs/automations/integrations/zapier/zapier-export-pr-number/README.md
  docs/automations/integrations/zapier/zapier-export-pr-reviewers/README.md
  docs/downloads/automation-library/integrations/slack/slack_auto_recognition.cm
  docs/downloads/automation-library/integrations/slack/slack_send_notification.cm
  docs/downloads/automation-library/integrations/zapier/zapier_export_pr_description_title_url.cm
  docs/downloads/automation-library/integrations/zapier/zapier_export_pr_number.cm
  docs/downloads/automation-library/integrations/zapier/zapier_export_pr_number_title_url.cm
  docs/downloads/automation-library/integrations/zapier/zapier_export_pr_reviewers.cm
  docs/downloads/images/integrations/zapier/zap-cal-1.png
  docs/downloads/images/integrations/zapier/zap-cal-2.png
  docs/downloads/images/integrations/zapier/zap-cal-3.png
  docs/downloads/images/integrations/zapier/zap-cal-4.png
  docs/downloads/images/integrations/zapier/zap-cal-5.png
  docs/downloads/images/integrations/zapier/zap-pm-1.png
  docs/downloads/images/integrations/zapier/zap-pm-2.png
  docs/downloads/images/integrations/zapier/zap-pre-1.png
  docs/downloads/images/integrations/zapier/zap-pre-2.png
  docs/downloads/images/integrations/zapier/zap-table-1.png
  docs/downloads/images/integrations/zapier/zap-table-2.png
  docs/downloads/images/integrations/zapier/zap-table-4.png
  docs/integrations/README.md
  docs/integrations/slack.md
  docs/integrations/zapier.md
Labels: examples-code-changes, 10 min review

#437 Small fix to Slack page.
  docs/automations/integrations/slack/slack-auto-recognition/README.md
  docs/automations/integrations/slack/slack-send-notification/README.md
Labels: 1 min review, no screenshot

#438 Create MS Teams Integration pages
  docs/automations/integrations/teams/teams-auto-recognition/README.md
  docs/automations/integrations/teams/teams-send-notification/README.md
  docs/downloads/automation-library/integrations/teams/teams_auto_recognition.cm
  docs/downloads/automation-library/integrations/teams/teams_send_notification.cm
  docs/downloads/images/integrations/teams/teams-pre-1.png
  docs/downloads/images/integrations/teams/teams-pre-2.png
  docs/downloads/images/integrations/teams/teams-pre-3.png
  docs/integrations/README.md
  docs/integrations/teams.md
Labels: 5 min review, examples-code-changes

#442 Small copyedit
  README.md
Labels: 1 min review

#445 Fix prevent com
  .cm/gitstream.cm
  docs/how-it-works.md
Labels: cm-changes

#443 Create review orca alerts automation
  docs/automations/integrations/orca/review-orca-alerts/README.md
  docs/automations/integrations/orca/review-orca-alerts/review-orca-alerts-1-dark.png
  docs/automations/integrations/orca/review-orca-alerts/review-orca-alerts-1-light.png
  docs/automations/integrations/orca/review-orca-alerts/review-orca-alerts-2-dark.png
  docs/automations/integrations/orca/review-orca-alerts/review-orca-alerts-2-light.png
  docs/downloads/automation-library/integrations/orca/review_orca_alerts.cm
  docs/integrations/orca-security.md
Labels: 5 min review, examples-code-changes

#448 Add Orca Logo to Integrations Page
  docs/downloads/images/Orca-Mark-Black.png
  docs/downloads/images/Orca-Mark-White.png
  docs/downloads/images/orca-logo-dark-mode.png
  docs/downloads/images/orca-logo-light-mode.png
  docs/integrations/README.md
Labels: 1 min review
