Repository linear-b/gitstream, pull requests merged in 2024-06, with the labels that each got.

#524 typo fix
  docs/automations/approve-tests/README.md
Labels: 1 min review, no screenshot

#526 added some better texts
  docs/execution-model.md
Labels: 1 min review

#527 change image
  docs/how-it-works.md
  docs/screenshots/automation-ui.png
Labels: 1 min review

#528 added python 3
  docs/github-installation.md
Labels: 1 min review

#535 added tips section
  docs/plugins.md
  docs/screenshots/playground-context-variables.png
  plugins/filters/banana/index.js
Labels: 1 min review

#536 new arg to explaincodeExperts
  docs/automation-actions.md
Labels: 1 min review

#537 typo
  docs/automation-actions.md
Labels: 1 min review

#538 Action update desc
  docs/automation-actions.md
Labels: 5 min review

#539 concat_mode
  docs/automation-actions.md
Labels: 1 min review

#541 add and remove quickstart
  docs/automations/approve-tests/README.md
  docs/automations/integrations/copilot/flag-copilot-pr/README.md
  docs/automations/integrations/dependabot/approve-dependabot/README.md
  docs/automations/integrations/orca/review-orca-alerts/README.md
  docs/automations/integrations/renovate/approve-renovate/README.md
  docs/automations/integrations/sonar/label-sonar/README.md
  docs/automations/provide-estimated-time-to-review/README.md
  docs/automations/request-screenshot/README.md
  docs/automations/standard/label-management/label-unresolved-threads/README.md
  docs/automations/standard/link-issue-tracker/README.md
  docs/automations/welcome-newcomer/README.md
Labels: 5 min review, no screenshot

#540 new update-title action
  docs/automation-actions.md
Labels: 1 min review

#534 new setup instruction for GHES
  docs/assets/gitstream-black.png
  docs/assets/gitstream-white.png
  docs/custom-github-app.md
  docs/screenshots/create-new-github-app-config.png
  docs/screenshots/create-new-github-app-pkey.png
  docs/screenshots/create-new-github-app-setup-permissions-1.png
  docs/screenshots/create-new-github-app-setup-permissions-2.png
  docs/screenshots/create-new-github-app-setup-permissions-3.png
  docs/screenshots/create-new-github-app-setup-permissions-4.png
  docs/screenshots/create-new-github-app-setup-permissions-5.png
  docs/screenshots/create-new-github-app-setup-permissions-6.png
  docs/screenshots/create-new-github-app-setup-permissions-7.png
  docs/screenshots/create-new-github-app-setup-post-installation.png
  docs/screenshots/create-new-github-app-setup-register.png
  docs/screenshots/create-new-github-app.png
  mkdocs.yml
Labels: 5 min review

#542 added pr source
  docs/context-variables.md
Labels: 1 min review

#543 Fix todo example
  docs/downloads/automation-library/standard/review-todo-comments/review_todo_comments.cm
Labels: 1 min review, examples-code-changes
