Repository linear-b/gitstream, pull requests merged in 2024-07, with the labels that each got.

#544 GitHub server fixes
  docs/custom-github-app.md
  docs/downloads/github/gitstream.cm
  docs/screenshots/choose-repo-access-for-new-github-app.png
  docs/screenshots/create-new-github-app-config.png
  docs/screenshots/create-new-github-app-setup-post-installation.png
  docs/screenshots/create-new-github-app-setup-register.png
  docs/screenshots/setup-linearb-github-server-step-1.png
  docs/screenshots/setup-linearb-github-server-step-2.png
  docs/screenshots/setup-new-github-app.png
Labels: 5 min review, examples-code-changes

#545 GitHub server more fixes
  docs/custom-github-app.md
Labels: 1 min review

#547 moved tips
  docs/custom-github-app.md
Labels: 1 min review

#548 fix githup app image checkbox
  docs/screenshots/create-new-github-app-setup-register.png
Labels: 1 min review

#549 fix name to match the automation purpose
  docs/downloads/automation-library/languages/css/review_css_important.cm
Labels: 1 min review, examples-code-changes

#550 fix names to be unique and match the docs
  docs/downloads/automation-library/integrations/github-actions/dispatch-github-action/dispatch_github_action_branch.cm
  docs/downloads/automation-library/integrations/github-actions/dispatch-github-action/dispatch_github_action_label.cm
  docs/downloads/automation-library/integrations/github-actions/dispatch-github-action/dispatch_github_action_resource.cm
  docs/downloads/automation-library/integrations/terraform/review_terraform_module_name.cm
Labels: 5 min review, examples-code-changes

#551 allowlist ips for Github App
  docs/custom-github-app.md
Labels: 1 min review

#553 Admin restrictions
  docs/cm-file.md
Labels: 1 min review

#554 add thread documentation
  docs/automation-actions.md
Labels: 1 min review

#556 Update automation-actions.md
  docs/automation-actions.md
Labels: 1 min review

#555 added github server
  docs/index.md
  mkdocs.yml
Labels: 1 min review

#558 fix typo in path of `.gitstream`
  docs/custom-github-app.md
Labels: 1 min review
