Repository linear-b/gitstream, pull requests merged in 2024-03, with the labels that each got.

#380 Soc2 Integration Page
  docs/automations/standard/flag-merged-no-review/README.md
  docs/automations/standard/flag-merged-no-review/flag-merged-no-review.png
  docs/automations/standard/flag-merged-no-review/slack-message.png
  docs/downloads/automation-library/standard/flag_merged_no_review.cm
  docs/integrations/README.md
  docs/integrations/soc2.md
Labels: 5 min review, examples-code-changes

#467 check if new python files added
  docs/filter-functions.md
Labels: 1 min review, no screenshot

#468 documenting comment edit trigger
  docs/changelog.md
  docs/execution-model.md
Labels: 1 min review

#470 remove triggers for it to work properly
  docs/downloads/automation-library/integrations/copilot/label_copilot_by_prompt.cm
Labels: 1 min review, examples-code-changes

#469 document GitLab request-changes
  docs/automation-actions.md
  docs/changelog.md
Labels: 1 min review

#471 change text for draft prs
  docs/execution-model.md
  docs/how-it-works.md
Labels: 1 min review, no screenshot

#474 new SVGs
  docs/automations/integrations/asana/label-missing-asana/asana.svg
  docs/automations/integrations/asana/link-asana/asana.svg
  docs/automations/integrations/azure-boards/label-missing-azure-boards/microsoft-azure.svg
  docs/automations/integrations/azure-boards/link-azure-boards/microsoft-azure.svg
  docs/automations/integrations/copilot/flag-copilot-pr/github-copilot.svg
  docs/automations/integrations/dependabot/approve-dependabot/dependabot.svg
  docs/automations/integrations/github-actions/dispatch-github-action/github-actions.svg
  docs/automations/integrations/github-actions/skip-github-action/github-actions.svg
  docs/automations/integrations/godoc/review-godoc-large/go-logo_blue.svg
  docs/automations/integrations/godoc/review-godoc-new-class/go-logo_blue.svg
  docs/automations/integrations/godoc/review-godoc/go-logo_blue.svg
  docs/automations/integrations/javadoc/review-javadoc-input-parameters/java-horizontal.svg
  docs/automations/integrations/javadoc/review-javadoc-large-change/java-horizontal.svg
  docs/automations/integrations/javadoc/review-javadoc/java-horizontal.svg
  docs/automations/integrations/javadoc/review-new-class-javadoc/java-horizontal.svg
  docs/automations/integrations/jira/label-missing-jira-info/jira.svg
  docs/automations/integrations/jira/link-jira/jira.svg
  docs/automations/integrations/jit/label-jit-alerts/Jit.svg
  docs/automations/integrations/jit/review-jit-alerts/Jit.svg
  docs/automations/integrations/jit/review-jit-ignore-accept/Jit.svg
  docs/automations/integrations/jit/review-jit-secret/Jit.svg
  docs/automations/integrations/jsdoc/review-jsdoc-input/JavaScript.svg
  docs/automations/integrations/jsdoc/review-jsdoc-large/JavaScript.svg
  docs/automations/integrations/jsdoc/review-jsdoc-new-class/JavaScript.svg
  docs/automations/integrations/jsdoc/review-jsdoc/JavaScript.svg
  docs/automations/integrations/launch-darkly/label-ff-launch-darkly/launchdarkly.svg
  docs/automations/integrations/orca/label-orca-scan-results/orca-logo-black-digital.svg
  docs/automations/integrations/orca/label-orca-scan-results/orca-logo-light-mode-digital.svg
  docs/automations/integrations/orca/review-orca-alerts/orca-logo-light-mode-digital.svg
  docs/automations/integrations/renovate/approve-renovate/renovate.svg
  docs/automations/integrations/shortcut/label-missing-shortcut/shortcut-icon.svg
  docs/automations/integrations/shortcut/link-shortcut/shortcut-icon.svg
  docs/automations/integrations/slack/slack-auto-recognition/slack.svg
  docs/automations/integrations/slack/slack-send-notification/slack.svg
  docs/automations/integrations/snyk/approve-snyk/snyk.svg
  docs/automations/integrations/sonar/approve-sonar-clean-code/sonarcloud.svg
  docs/automations/integrations/sonar/label-sonar/sonarcloud.svg
  docs/automations/integrations/sonar/review-sonar-alerts/sonarcloud.svg
  docs/automations/integrations/sonar/review-sonar-duplications/sonarcloud.svg
  docs/automations/integrations/swimm/approve-swimm/swimm.svg
  docs/automations/integrations/teams/teams-auto-recognition/microsoft-teams.svg
  docs/automations/integrations/teams/teams-send-notification/microsoft-teams.svg
  docs/automations/integrations/terraform/review-new-module/terraform.svg
  docs/automations/integrations/terraform/review-terraform-module-name/terraform.svg
  docs/automations/integrations/terraform/review-terraform-source-version/terraform.svg
  docs/automations/integrations/terraform/review-terraform/terraform.svg
  docs/automations/integrations/zapier/zapier-export-pr-description-title-url/zapier.svg
  docs/automations/integrations/zapier/zapier-export-pr-number-title-url/zapier.svg
  docs/automations/integrations/zapier/zapier-export-pr-number/zapier.svg
  docs/automations/integrations/zapier/zapier-export-pr-reviewers/zapier.svg
Labels: 1 min review

#475 fix request-changes regex
  docs/automation-actions.md
Labels: 1 min review, no screenshot

#476 meta update
  docs/automations/integrations/azure-boards/link-azure-boards/README.md
  docs/automations/integrations/jira/label-missing-jira-info/README.md
  docs/automations/integrations/jira/link-jira/README.md
  docs/automations/standard/explain-code-experts/README.md
  docs/automations/standard/review-todo-comments/README.md
  docs/automations/welcome-newcomer/README.md
Labels: 5 min review, no screenshot

#477 add regex to ignore repos
  docs/changelog.md
  docs/cm-file.md
Labels: 1 min review
