Repository linear-b/gitstream, pull requests merged in 2024-08, with the labels that each got.

#560 added troubleshooting
  docs/troubleshooting.md
Labels: 1 min review

#561 add dependabot example to triggers reference
  docs/execution-model.md
Labels: 1 min review

#562 improve plugin sections
  docs/plugins.md
  mkdocs.yml
Labels: 1 min review

#564 new plugin that generates PR desc from conventional commits
  docs/filter-function-plugins.md
  docs/screenshots/generate-pr-description-example.png
  plugins/filters/generateDescription/LICENSE
  plugins/filters/generateDescription/README.md
  plugins/filters/generateDescription/auto_pr_description.cm
  plugins/filters/generateDescription/index.js
  plugins/filters/generateDescription/reference.md
Labels: examples-code-changes, 10 min review

#565 added section for Generate PR Description
  docs/automations/generate-pr-description/README.md
  docs/automations/generate-pr-description/generate-pr-description-example.png
  docs/downloads/automation-library/generate_pr_description.cm.cm
  plugins/filters/generateDescription/README.md
  plugins/filters/generateDescription/generate_pr_description.cm.cm
Labels: 5 min review, examples-code-changes

#567 fix typo "
  docs/automations/generate-pr-description/README.md
Labels: 1 min review

#530 Create checklist plugin
  docs/automations/automation-library.md
  docs/automations/pr-checklist-general/README.md
  docs/automations/pr-checklist-general/pr-checklist-general.png
  docs/downloads/automation-library/pr_checklist_general.cm
  docs/filter-function-plugins.md
  plugins/filters/checklist/LICENSE
  plugins/filters/checklist/README.md
  plugins/filters/checklist/index.js
  plugins/filters/checklist/reference.md
Labels: 5 min review, examples-code-changes

#570 changed webhooks image
  docs/screenshots/create-new-github-app-setup-permissions-5.png
Labels: 1 min review
