Repository linear-b/gitstream, pull requests merged in 2024-12, with the labels that each got.

#611 Refactor askAI plugin: improve file exclusion logic and enhance conttext
  plugins/filters/askAI/index.js
Labels: 1 min review

#613 fix capture return type
  docs/filter-functions.md
Labels: 1 min review

#618 Update execution-model.md
  docs/execution-model.md
Labels: 1 min review

#619 fix texts in execution
  docs/execution-model.md
Labels: 1 min review

#622 update run github workflow doc
  docs/automation-actions.md
Labels: 1 min review

#604 trigggers-refinement
  docs/execution-model.md
Labels: 1 min review

#623 Update gitstream.yml
  docs/downloads/gitstream.yml
Labels: 1 min review

#624 Update context-variables.md
  docs/context-variables.md
Labels: 1 min review, 1 Unresolved Thread(s)

#625 minor fixes for BB
  docs/bitbucket-installation.md
  docs/context-variables.md
  mkdocs.yml
Labels: 1 min review

#626 Update cm-file.md
  docs/cm-file.md
Labels: 1 min review, no screenshot

#627 Update bitbucket-installation.md
  docs/bitbucket-installation.md
  docs/gitlab-installation.md
Labels: 1 min review
