Repository linear-b/gitstream, pull requests merged in 2025-04, with the labels that each got.

#676 Update AI actions with all providers, template and guidelines
  docs/automation-actions.md
Labels: 1 min review

#678 Update LinearB-AI-describe-pr.png
  docs/automations/integrations/LinearBAI/describe-pr/LinearB-AI-describe-pr.png
Labels: 1 min review

#680 Add link to code-review action docs
  docs/automations/integrations/LinearBAI/code-review/README.md
Labels: 1 min review, no screenshot

#683 Add excluded files documentation for code review and changes
  docs/automation-actions.md
Labels: 1 min review

#685 Rename execution model documentation to trigger control
  docs/execution-model.md
  mkdocs.yml
Labels: 1 min review, no screenshot

#689 Measure ai
  docs/automations/integrations/ai-assistance/flag-ai-pr/README.md
  docs/automations/integrations/ai-assistance/flag-ai-pr/ask-ai-assistance.png
  docs/automations/integrations/ai-assistance/flag-ai-pr/label-ai-assistance.png
  docs/downloads/automation-library/integrations/ai-assistance/comment_ai_prompt.cm
  docs/downloads/automation-library/integrations/ai-assistance/comment_ai_prompt_with_known_users.cm
  docs/downloads/automation-library/integrations/ai-assistance/track_ai_models.cm
  docs/downloads/automation-library/integrations/copilot/comment_copilot_prompt.cm
  docs/downloads/automation-library/integrations/copilot/label_copilot_by_contributors.cm
  docs/integrations/README.md
Labels: 5 min review, examples-code-changes, 1 Unresolved Thread(s)

#691 Update custom-github-app.md
  docs/custom-github-app.md
Labels: 1 min review, no screenshot

#692 Update bitbucket-installation.md
  docs/bitbucket-installation.md
Labels: 1 min review

#694 Update excluded file types for code review
  docs/automation-actions.md
Labels: 1 min review

#696 remove-triggers
  docs/downloads/gitStream-gl.cm
  docs/gitlab-installation.md
Labels: 1 min review, examples-code-changes

#690 📝 docs: automatically labeling Cursor-assisted PRs
  docs/automations/integrations/cursor/flag-cursor-pr/README.md
  docs/automations/integrations/cursor/flag-cursor-pr/label-cursor-by-contributors.png
  docs/automations/integrations/cursor/flag-cursor-pr/label-cursor-by-prompt.png
  docs/automations/integrations/cursor/flag-cursor-pr/label-cursor-by-tag.png
  docs/automations/integrations/cursor/flag-cursor-pr/logo_flag_cursor_pr.png
  docs/downloads/automation-library/integrations/cursor/comment_cursor_prompt.cm
  docs/downloads/automation-library/integrations/cursor/label_cursor_by_contributors.cm
  docs/downloads/automation-library/integrations/cursor/label_cursor_by_prompt.cm
  docs/downloads/automation-library/integrations/cursor/label_cursor_by_tag.cm
  docs/integrations/README.md
  docs/integrations/cursor.md
Labels: 5 min review, examples-code-changes

#698 added troubleshooting
  docs/troubleshooting.md
Labels: 1 min review, no screenshot

#697 Add 'on' event triggers to Dependabot automation examples
  docs/downloads/automation-library/integrations/dependabot/approve_dependabot.cm
  docs/downloads/automation-library/integrations/dependabot/approve_dependabot_minor.cm
  docs/execution-model.md
  docs/stylesheets/extra.css
  plugins/filters/extractDependabotVersionBump/extract_dependabot_version_bump.cm
Labels: 5 min review, examples-code-changes

#700 Add triggers to suggest-code-experts examples
  docs/automations/standard/explain-code-experts/README.md
  docs/downloads/automation-library/standard/explain_code_experts.cm
  docs/downloads/gitStream-gl.cm
  docs/downloads/github/gitstream.cm
  docs/downloads/gitstream.cm
  docs/downloads/sales_demo.cm
Labels: 5 min review, examples-code-changes, no screenshot
