Repository linear-b/gitstream, pull requests merged in 2025-02, with the labels that each got.

#649 Remove license badge to avoid confusion
  README.md
Labels: 1 min review

#650 added info on limits
  docs/execution-model.md
  docs/faq.md
  docs/index.md
  docs/limits.md
  mkdocs.yml
Labels: 5 min review, LB CR

#651 Add uv.lock to exclude list
  plugins/filters/askAI/index.js
Labels: 1 min review, 1 Unresolved Thread(s)

#652 add images to safe changes
  docs/automations/approve-safe-changes/README.md
Labels: 1 min review

#653 Update gitlab-ci.yml
  docs/downloads/gitlab-ci.yml
Labels: 1 min review
