Repository linear-b/gitstream, pull requests merged in 2025-05, with the labels that each got.

#701 📝 docs: automatically labeling Windsurf-assisted PRs
  docs/automations/integrations/cursor/flag-cursor-pr/README.md
  docs/automations/integrations/windsurf/flag-windsurf-pr/README.md
  docs/automations/integrations/windsurf/flag-windsurf-pr/label-windsurf-by-contributors.png
  docs/automations/integrations/windsurf/flag-windsurf-pr/label-windsurf-by-prompt.png
  docs/automations/integrations/windsurf/flag-windsurf-pr/label-windsurf-by-tag.png
  docs/automations/integrations/windsurf/flag-windsurf-pr/logo_flag_cursor_pr.png
  docs/downloads/automation-library/integrations/windsurf/comment_windsurf_prompt.cm
  docs/downloads/automation-library/integrations/windsurf/label_windsurf_by_contributors.cm
  docs/downloads/automation-library/integrations/windsurf/label_windsurf_by_prompt.cm
  docs/downloads/automation-library/integrations/windsurf/label_windsurf_by_tag.cm
  docs/integrations/README.md
  docs/integrations/windsurf.md
Labels: 5 min review, examples-code-changes, 🤖 ai-cursor

#703 link to support instead of github issues
  docs/faq.md
Labels: 1 min review, no screenshot

#704 dry run improvements
  docs/dry-run-mode.md
Labels: 1 min review, no screenshot

#706 Bot detection ai cm
  docs/downloads/gitStream-gl.cm
  docs/downloads/gitstream.cm
Labels: 1 min review, examples-code-changes

#707 Add repository filtering docs for organization-level rules
  docs/cm-file.md
Labels: 1 min review, no screenshot, 🤖 ai-other

#708 📝 docs: automatically labeling Claude Code-assisted PRs
  docs/automations/integrations/claude-code/flag-claude-code-pr/README.md
  docs/automations/integrations/claude-code/flag-claude-code-pr/label-claude-code-by-contributors.png
  docs/automations/integrations/claude-code/flag-claude-code-pr/label-claude-code-by-prompt.png
  docs/automations/integrations/claude-code/flag-claude-code-pr/label-claude-code-by-tag.png
  docs/downloads/automation-library/integrations/claude_code/comment_claude_code_prompt.cm
  docs/downloads/automation-library/integrations/claude_code/label_claude_code_by_contributors.cm
  docs/downloads/automation-library/integrations/claude_code/label_claude_code_by_prompt.cm
  docs/downloads/automation-library/integrations/claude_code/label_claude_code_by_tag.cm
  docs/integrations/README.md
  docs/integrations/claude-code.md
Labels: 5 min review, examples-code-changes

#711 Fix integrations right panel missing examples
  docs/automations/integrations/javadoc/review-javadoc-input-parameters/README.md
  docs/automations/integrations/javadoc/review-javadoc-large-change/README.md
  docs/automations/integrations/javadoc/review-javadoc/README.md
  docs/automations/integrations/javadoc/review-new-class-javadoc/README.md
  docs/automations/integrations/jit/label-jit-alerts/README.md
  docs/automations/integrations/jit/review-jit-alerts/README.md
  docs/automations/integrations/jit/review-jit-ignore-accept/README.md
  docs/automations/integrations/jit/review-jit-secret/README.md
  docs/automations/integrations/jsdoc/review-jsdoc-input/README.md
  docs/automations/integrations/jsdoc/review-jsdoc-large/README.md
  docs/automations/integrations/jsdoc/review-jsdoc-new-class/README.md
  docs/automations/integrations/jsdoc/review-jsdoc/README.md
  docs/automations/integrations/sonar/approve-sonar-clean-code/README.md
  docs/automations/integrations/sonar/label-sonar/README.md
  docs/automations/integrations/sonar/review-sonar-duplications/README.md
  docs/automations/integrations/terraform/review-new-module/README.md
  docs/automations/integrations/terraform/review-terraform-module-name/README.md
  docs/automations/integrations/terraform/review-terraform-source-version/README.md
  docs/automations/integrations/terraform/review-terraform/README.md
  docs/integrations/LB_AI.md
  docs/integrations/askAI.md
  docs/integrations/claude-code.md
  docs/integrations/cursor.md
  docs/integrations/github-copilot.md
  docs/integrations/godoc.md
  docs/integrations/javadoc.md
  docs/integrations/jit.md
  docs/integrations/jsdoc.md
  docs/integrations/rdoc.md
  docs/integrations/sonar.md
  docs/integrations/terraform.md
Labels: 20 min review

#712 Improve Dependabot version extraction to support "Updates" pattern
  plugins/filters/extractDependabotVersionBump/index.js
  plugins/filters/extractDependabotVersionBump/test.js
Labels: 5 min review

#710 Fix Dependabot version extraction by parsing JSON description
  plugins/filters/extractDependabotVersionBump/index.js
Labels: 1 min review, 🤖 ai-none

#709 📝 docs: automatically labeling Amazon Q-assisted PRs
  docs/automations/integrations/amazon-q/flag-amazon-q-pr/README.md
  docs/automations/integrations/amazon-q/flag-amazon-q-pr/label-amazon-q-by-contributors.png
  docs/automations/integrations/amazon-q/flag-amazon-q-pr/label-amazon-q-by-prompt.png
  docs/automations/integrations/amazon-q/flag-amazon-q-pr/label-amazon-q-by-tag.png
  docs/downloads/automation-library/integrations/amazon_q/comment_amazon_q_prompt.cm
  docs/downloads/automation-library/integrations/amazon_q/label_amazon_q_by_contributors.cm
  docs/downloads/automation-library/integrations/amazon_q/label_amazon_q_by_prompt.cm
  docs/downloads/automation-library/integrations/amazon_q/label_amazon_q_by_tag.cm
  docs/integrations/README.md
  docs/integrations/amazon-q.md
Labels: 5 min review, examples-code-changes, 🤖 ai-cursor

#713 Use template syntax for tracker URLs
  docs/downloads/automation-library/integrations/azure-boards/link_azure_boards.cm
  docs/downloads/automation-library/integrations/jira/link_jira.cm
  docs/downloads/automation-library/integrations/shortcut/link_shortcut.cm
  docs/downloads/automation-library/standard/link_issue_tracker.cm
Labels: 5 min review, examples-code-changes

#714 Alphabetize and standardize trigger events table in docs
  docs/execution-model.md
Labels: 1 min review, no screenshot

#716 Add AI Rules section for Copilot and Cursor PRs
  docs/automations/integrations/copilot/flag-copilot-pr/README.md
  docs/automations/integrations/cursor/flag-cursor-pr/README.md
  docs/downloads/automation-library/integrations/copilot/copilot-instructions.md
  docs/downloads/automation-library/integrations/copilot/label_copilot_by_rule.cm
  docs/downloads/automation-library/integrations/cursor/cursor-ai-logging.mdc
  docs/downloads/automation-library/integrations/cursor/label_cursor_by_rule.cm
Labels: 5 min review, examples-code-changes, no screenshot, 1 Unresolved Thread(s)

#717 Revert AI logging
  docs/automations/integrations/copilot/flag-copilot-pr/README.md
  docs/automations/integrations/cursor/flag-cursor-pr/README.md
  docs/downloads/automation-library/integrations/copilot/copilot-instructions.md
  docs/downloads/automation-library/integrations/copilot/label_copilot_by_rule.cm
  docs/downloads/automation-library/integrations/cursor/cursor-ai-logging.mdc
  docs/downloads/automation-library/integrations/cursor/label_cursor_by_rule.cm
Labels: 5 min review, no screenshot

#719 update docs with bitbucket triggers warning
  docs/bitbucket-installation.md
  docs/gitlab-installation.md
Labels: 1 min review, no screenshot, 1 Unresolved Thread(s)

#721 Fix typo on Copilot docs
  docs/automations/integrations/copilot/flag-copilot-pr/README.md
Labels: 1 min review, no screenshot

#722 Add detailed IP allowlisting explanation for all Git providers
  docs/bitbucket-installation.md
  docs/github-installation.md
  docs/gitlab-installation.md
Labels: 5 min review, 1 Unresolved Thread(s)

#723 fix the bullet list not showing up correctly
  docs/bitbucket-installation.md
  docs/github-installation.md
  docs/gitlab-installation.md
Labels: 1 min review, 🤖 ai-other

#724 Exclude askAI docs from search results
  docs/automations/integrations/askAI/add-tests/README.md
  docs/automations/integrations/askAI/code-review/README.md
  docs/automations/integrations/askAI/document/README.md
  docs/automations/integrations/askAI/improve/README.md
  docs/automations/integrations/askAI/summarize-pr/README.md
  docs/integrations/askAI.md
Labels: 5 min review

#725 Improve instructions for adding code review guidelines
  docs/automation-actions.md
  docs/automations/integrations/LinearBAI/code-review/README.md
  docs/downloads/automation-library/integrations/LinearBAI/code-review-bb.cm
  docs/downloads/automation-library/integrations/LinearBAI/code-review-gl.cm
  docs/downloads/automation-library/integrations/LinearBAI/code-review.cm
  docs/integrations/LB_AI.md
Labels: 5 min review, examples-code-changes

#728 Add tip about multi-org GitHub app installation support
  docs/custom-github-app.md
Labels: 1 min review

#730 change link check so it match only new additions and do not alert on old
  .cm/gitstream.cm
Labels: cm-changes

#731 ignore the specific sentance in the README
  .cm/gitstream.cm
Labels: cm-changes
